apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: app
          image: akhouridocker24/springboot-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/devdb
            - name: SPRING_DATASOURCE_USERNAME
              value: devuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: devpass